### ISSUE TITLE
`cyan` variable undefined in color schemes

### ISSUE THREAD

**Issue by jrappen** [mauroreisvieira/github-sublime-theme#4]
As stated in the console upon startup:

```text
Unable to parse color value var(cyan) at Packages/User/Github Dark.sublime-color-scheme:53:29
Unable to parse color value color(var(cyan) alpha(0.1)) at Packages/User/Github Dark.sublime-color-scheme:44:38
```

the variable `cyan` is undefined in the `GitHub Dark` color scheme. Same for `GitHub Light`.

---

```yaml
GitHub Sublime Theme:
  version: v1.3.0

Sublime Text:
  build: 4074
  channel: dev
    portable: false
  platform: osx x64

System:
  hardware: MBP 15" 2018, i9 2.9GHz, 32GB, 1TB, Radeon Pro 560X
  software: macOS Catalina 10.15.5 (19F101)
    open_gl:
      gl_api_version: 4.1 INTEL-14.6.18
      glsl_version: 4.10
      vendor: Intel Inc.
      renderer: Intel(R) UHD Graphics 630
```
